### Honors & Awards

| Award | Date |
|---|---|
| Fulbright Specialist | August 2026 |
| Top-3 Finalist at a Deep Learning Research Symposium | November 2023 |
| Goizueta Fellowship at Georgia Tech | August 2022 |
| Summa Cum Laude Honors at University of Texas at Arlington | May 2022 |
| Honors College Degree Requirements at University of Texas at Arlington | December 2021 |
| Electrical Engineering Honors Scholar at University of Texas at Arlington | December 2021 |
| IEEE-HKN International Electrical Engineering Honor Society Membership | August 2021 |
| Research Experience for Undergraduates Fellowship Recipient | August 2020 |
| Chance Vought Engineering and Science Endowment Scholarship | August 2020 |
| Toray Composite Materials America Inc. Sons and Daughters Scholarship | May 2019 |
| James E. Casey Scholarship Recipient | January 2019 |
| James R. Hoffa Memorial Scholarship Recipient | May 2018 |
| Grapevine, TX Rotary Club Scholarship Recipient | May 2018 |
| National Hispanic Scholar | March 2018 |
| National Merit Scholar | March 2018 |
