### Service & Leadership

**Co-Founder and President of Puerto Rican Student Association** | Georgia Institute of Technology | Atlanta, GA\
*August 2024 - Present*

- Addressed the need for an organization to help Puerto Rican students feel at home and stay connected to our culture
- Formed a three-member co-founder board and identified a faculty advisor
- Raised funds for the organization and recruited members from campus
- Hosted professional, social, and cultural events to meet the needs of the growing Puerto Rican student population at Georgia Tech

**Undergraduate Research Mentor** | University of Texas at Arlington | Arlington, TX\
*August 2021 - May 2022*

- As the lead undergraduate student in Dr. Frank Lewis' Autonomous Systems Lab, mentored junior undergrads in controls research and guided them on a research project in ground vehicle control
- Guided students in Robot Operating System, Python, Linux, and Control Systems

**Eta Kappa Nu Public Relations Chair & Circuits I Tutor** | University of Texas at Arlington | Arlington, TX\
*August 2020 - May 2022*

- Executive board member of UT Arlington's IEEE-HKN chapter
- In charge of social media advertising for the honor society's events and outreach initiatives for the electrical engineering student body
- Volunteered to provide free tutoring as a service to electrical engineering students in Circuits I
